#
# BRAD's HA CONFIG
# LIVING IN THE FUTURE
#

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 7
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include config/customize.yaml
  customize_glob: !include config/custom-ui.yaml

recorder:
  purge_days: 2
#logger:
#  default: debug
frontend:
http:
  api_password: !secret http_password
updater:
history:
sun:
wemo:

# Custom UI Panels
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include config/floorplan.yaml

#
# Split configuration into separate files
#
device_tracker: !include config/device_tracker.yaml
zone: !include config/zones.yaml
scene: !include_dir_merge_list scenes
script: !include_dir_merge_named scripts
python_script:
input_boolean: !include config/input_boolean.yaml
input_slider: !include config/input_slider.yaml
input_select: !include config/input_select.yaml
sensor: !include config/sensors.yaml
binary_sensor: !include config/binary_sensors.yaml
switch: !include config/switches.yaml
automation: !include_dir_merge_list automation
logbook: !include config/logbook.yaml
shell_command: !include config/shell.yaml
plant: !include config/plants.yaml
media_player: !include config/media_players.yaml
mqtt: !include config/mqtt.yaml

#
# Additional Platforms
#
alarm_control_panel:
  - platform: manual
    name: Loft Alarm
    pending_time: 45
    trigger_time: 120
camera: !include config/cameras.yaml
light: !include config/lights.yaml
ios:
emulated_hue:
  listen_port: 8300
  expose_by_default: false
tradfri:
  host: 192.168.0.9
  api_key: !secret ikea_key
ifttt:
  key: !secret ifttt_key
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 3600

#
# Set up Communication Hardware
#
# This causes HA to hang :( :(
#zha:
#  usb_path: /dev/ttyUSB1
#  database_path: /home/homeassistant/.homeassistant/zigbee.db
zwave:
  usb_path: /dev/ttyUSB0
  new_entity_ids: true
  config_path: /usr/local/lib/python3.4/dist-packages/python_openzwave/ozw_config
  polling_interval: 30000
  device_config:
    light.back_overheads:
      refresh_value: true
      delay: 5
      polling_intensity: 1
    light.front_overheads:
      refresh_value: true
      delay: 5
      polling_intensity: 1
    switch.bathroom_light:
      refresh_value: true
      polling_intensity: 1
    switch.bathroom_fan:
      refresh_value: true
      polling_intensity: 1
    switch.kitchen_lights:
      refresh_value: true
      polling_intensity: 1

###########################
## ORGANIZE INTO GROUPS  ##
###########################

group:
  # REPLACE HOME PAGE
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.Scenes
      - group.AlarmClock
      - camera.car_location
      - group.Alarm
      - group.traveltimes
#      - camera.east_bay
  Lights:
    view: yes
    icon: mdi:flash
    entities:
      - group.Bathroom
      - group.Bedroom
      - group.Kitchen
      - group.LivingRoom
      - group.Office
      - group.Overheads
      - group.Misc
  # CLIMATE TAB
  Climate:
    view: yes
    icon: mdi:thermometer
    entities:
      - camera.sf_radar
      - group.Weather
      - group.Today
      - group.Indoors
      - group.Temperatures
  # MEDIA TAB
  Media:
    view: yes
    icon: mdi:filmstrip
    entities:
      - group.Radio
      - media_player.roku_3__4124cg078650
      - group.Speakers
      - group.Downloads
  # MONITORING TAB
  Cameras:
    view: yes
    icon: mdi:eye
    entities:
      - group.Motion
      - group.Openings
      - camera.front_door
      - camera.east_bay
      - camera.window
  Information:
    view: yes
    icon: mdi:barley
    entities:
      - group.Plants
      - group.Aquarium
  # SYSTEM TAB
  System:
    view: yes
    icon: mdi:gauge
    entities:
      - group.BradsDevices
      - group.SystemOptions
      - group.Devices
      - group.Pi

# TRACKED USERS
  tracked_users:
    view: no
    name: Tracked Users
    entities:
      - input_boolean.bradhome 
      - input_boolean.guesthome
# SMALLER GROUPS FOR ABOVE TABS
#

# Alarm Alarm
  Alarm:
    control: hidden
    name: Alarm
    entities:
      - group.alarmbadge
      - script.alarm_disarm
      - script.alarm_arm_home
      - input_boolean.alarm_override
# Alarm Status Badge
  alarmbadge:
    entities:
      - alarm_control_panel.loft_alarm
      - group.tracked_users
      - input_boolean.guest_mode
      - input_boolean.vacation_mode
# Alarm Clock
  AlarmClock:
    control: hidden
    name: Alarm Clock
    entities:
      - automation.alarm_clock
      - sensor.alarm_time
      - input_slider.alarmhour
      - input_slider.alarmminutes
      - input_boolean.alarmweekday
      - sensor.coffeemaker
  Bathroom:
    name: Bathroom
    entities:
      - switch.bathroom_light
      - switch.bathroom_fan
  BradsDevices:
    name: "Brad"
    entities:
      - group.bradsdevicesbadges
      - input_boolean.bradhome
      - sensor.battery_iphone
      - sensor.breaches_bradbradwennercom
  bradsdevicesbadges:
    entities:
      - device_tracker.bradwenner_ios
      - device_tracker.bradwenner_owntracks
      - device_tracker.bradwenner_ping
  Devices:
    name: Devices
    entities:
      - group.devicebadges
      - sensor.synology_storage_free
  devicebadges:
    entities:
      - sensor.synology_online
      - sensor.bradlaptop_online
      - sensor.ikeatradfri_online
      - sensor.espmilight_online
      - sensor.windowcam_online
      - sensor.frontdoorcam_online
      - sensor.laserprinter_online
  Indoors:
    name: Indoor Air Quality
    entities:
      - group.environmentbadges
  environmentbadges:
    entities:
      - sensor.kitchen_smoke
      - sensor.kitchen_humidity
      - sensor.carbon_monoxide
      - sensor.air_pressure
  Overheads:
    entities:
      - light.front_overheads
      - light.back_overheads
  Plants:
    entities:
      - sensor.water_plants
      - plant.rubber_plant
      - plant.giant_pothos
      - plant.giant_philodendron
      - plant.palm
      - plant.projector_pothos
      - plant.hanging_red_pothos
      - plant.hanging_spider_plant
      - plant.kitchen_pothos
      - plant.small_philodendron
      - plant.window_spider_plant
  Bedroom:
    entities:
    - light.entry
    - light.closet
    - light.bedroom
    - switch.bedroom_fan
  Kitchen:
    control: hidden
    entities:
    - switch.kitchen_lights
    - switch.edison_pendants
    - switch.string_lights
    - light.stove
    - light.fridge
    - switch.sink
    - switch.coffeemaker
  LivingRoom:
    name: Living Room
    entities:
    - light.back_overheads
    - light.globes
    - light.floor_lamp
    - light.dining_floor_lamp
    - switch.aquarium
  Office:
   entities:
    - switch.office
    - light.office_pendant
    - switch.work_lamp
  Grocery_Zone:
    name: Near Grocery
    entities:
    - zone.whole_foods
    - zone.sprouts_market
    - zone.grocery_outlet
    - zone.lucky_grocery
  Scenes:
    control: hidden
    entities:
    - scene.day_dim_lights
    - scene.evening_bright_lights
    - scene.night_dim_lights
    - scene.all_lights_off
    - scene.all_lights_on
  Today:
    entities:
    - group.todaybadges
    - sensor.friendly_date
    - sensor.dark_sky_hourly_summary
  todaybadges:
    entities:
    - sun.sun
    - sensor.solar_angle
    - sensor.sunrise_time
    - sensor.sunset_time
    - sensor.moon
  Speakers:
    entities:
    - switch.mpd_pi
    - input_slider.radiovolume
    - sensor.nowplaying_pi
    - switch.volumio
    - input_slider.stereovolume
    - sensor.nowplaying_volumio
  SystemOptions:
    name: Home Options
    entities:
    - group.tracked_users
    - input_boolean.vacation_mode
    - input_boolean.guest_mode
    - switch.flux
  Motion:
    entities:
    - sensor.last_motion
    - group.motionbadges
  motionbadges:
    entities:
    - binary_sensor.entry_motion
    - binary_sensor.closet_motion
    - binary_sensor.bathroom_motion
    - binary_sensor.kitchen_motion
    - binary_sensor.dining_motion
  Openings:
    entities:
    - group.openingsbadges
  openingsbadges:
    entities:
    - binary_sensor.front_door
    - binary_sensor.crawl_space_door
    - binary_sensor.left_window
  Aquarium:
    entities:
    - switch.aquarium
    - binary_sensor.left_window 
    - sensor.window_air_temp
    - sensor.water_temperature
  Misc:
    - light.crawl_space
    - switch.extra_plug
  Pi:
    name: HomeAssistant Pi
    control: hidden
    entities:
      - group.pibadges
      - sensor.since_last_boot
      - script.restart_ha
      - switch.pi_shutdown
      - switch.pi_reboot
  pibadges:
    entities:
      - sensor.ram_use
      - sensor.cpu_use
      - sensor.disk_use_
      - sensor.disk_free_
  Radio:
    name: Radio
    control: hidden
    entities:
      - input_slider.radiovolume
      - switch.radio_npr
      - switch.radio_kalx
      - switch.radio_jazz
      - switch.radio_metal
      - switch.radio_kzsc
  Weather:
    entities:
      - group.weatherbadges
      - group.weatherconditionsbadges
      - sensor.dark_sky_daily_summary
      - group.weatherforecastbadges
  weatherbadges:
    entities:
      - sensor.yr_symbol
      - sensor.dark_sky_temperature
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
  weatherconditionsbadges:
    entities:
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_cloud_coverage
      - sensor.yr_fog
      - sensor.friendly_wind_direction
      - sensor.dark_sky_wind_speed
  weatherforecastbadges:
    entities:
      - sensor.dark_sky_daily_high_temperature_1
      - sensor.dark_sky_daily_low_temperature_1
      - sensor.dark_sky_precip_probability_1
      - sensor.dark_sky_cloud_coverage_1
      - sensor.friendly_wind_direction_forecast
  Temperatures:
    entities:
      - group.temperaturebadges
  temperaturebadges:
    entities:
      - sensor.entry_temperature
      - sensor.kitchen_pothos_temperature
      - sensor.giant_pothos_temperature
      - sensor.hanging_red_pothos_temperature
      - sensor.window_air_temp
  TravelTimes:
    name: Travel Times
    entities:
      - sensor.current_location_to_home
      - sensor.current_location_to_studio
      - sensor.home_to_16th_mission_bart
      - sensor.home_to_richmond_Bart
  Downloads:
    entities:
      - sensor.transmission_status
      - switch.transmission_turtle_mode
      - group.transmissionbadges
      - sensor.sabnzbd_status
      - group.sabnzbdbadges
  transmissionbadges:
    entities:
      - sensor.transmission_down_speed_kbps
      - sensor.transmission_up_speed_kbps
  sabnzbdbadges:
    entities:
      - sensor.sabnzbd_speed
      - sensor.sabnzbd_left
      - sensor.sabnzbd_queue
