#
# Binary Sensor from Android IP Cam
#
- platform: template
  sensors:
    fridge_motion:
      value_template: '{{ states.sensor.ip_webcam_motion.state | float > 700 }}'
      friendly_name: Fridge Motion
      device_class: motion

#
# META MOTION SENSORS
#

- platform: template
  sensors:
    dining_motion_meta:
      friendly_name: 'Dining Motion'
      device_class: motion
      value_template: >-
        {%- if is_state("binary_sensor.dining_motion", "on")
        or is_state("binary_sensor.dining_motion_2", "on")
          -%}
        True
        {%- else -%}
        False
        {%- endif %}
      entity_id:
        - binary_sensor.dining_motion
        - binary_sensor.dining_motion_2
    kitchen_motion_meta:
      friendly_name: 'Kitchen Motion'
      device_class: motion
      value_template: >-
        {%- if is_state("binary_sensor.kitchen_motion", "on")
        or is_state("binary_sensor.fridge_motion", "on")
          -%}
        True
        {%- else -%}
        False
        {%- endif %}

# Bruh Node Motion
- platform: mqtt
  state_topic: "BruhNode/LivingRoom"
  device_class: motion
  value_template: '{{ value_json.motion }}'
  payload_on: 'motion detected'
  payload_off: 'standby'
  name: "Dining Motion 2"


#
# Motion Sensor via RPI GPIO
#

- platform: mqtt
  state_topic: "PiNode/Motion/LivingRoom/Switch"
  device_class: motion
  payload_on: "1"
  payload_off: "0"
  name: "Living Room Motion"
- platform: mqtt
  state_topic: "PiNode/Motion/Dining/Switch"
  device_class: motion
  payload_on: "1"
  payload_off: "0"
  name: "Dining Motion"

#
# MOTION SENSORS VIA NODES
#
- platform: mqtt
  state_topic: "ClosetNode/Motion/Switch"
  device_class: motion
  payload_on: "1"
  payload_off: "0"
  name: "Closet Motion"

- platform: mqtt
  state_topic: "KitchenNode/Motion/Switch"
  device_class: motion
  payload_on: "1"
  payload_off: "0"
  name: "Kitchen Motion"

- platform: mqtt
  state_topic: "KitchenNode/Door/Switch"
  device_class: opening
  payload_on: "1"
  payload_off: "0"
  name: "Crawl Space Door"

- platform: mqtt
  state_topic: "FrontDoorNode/Motion/Switch"
  device_class: motion
  payload_on: "1"
  payload_off: "0"
  name: "Entry Motion"

- platform: mqtt
  state_topic: "FrontDoorNode/Door/Switch"
  device_class: opening
  payload_on: "1"
  payload_off: "0"
  name: "Front Door"

- platform: mqtt
  state_topic: "AquariumNode/Window/Switch"
  device_class: opening
  payload_on: "1"
  payload_off: "0"
  name: "Left Window"
