# Alarm
alarm_override:
  name: Alarm Override
  initial: off
  icon: mdi:cancel

# PRESENCE
vacation_mode:
  name: Vacation Mode
  initial: off
  icon: mdi:airplane
guest_mode:
  name: Guest Mode
  initial: off
  icon: mdi:account-multiple

# Group Presence Trackers
bradhome:
  name: Brad Home
  icon: mdi:account
guesthome:
  name: Guest Home
  initial: off
  icon: mdi:account-plus

alarmweekday:
  name: Weekdays Only
  initial: off
  icon: mdi:calendar
