# Alarm
alarm_override:
  name: Alarm Override
  initial: off
  icon: mdi:cancel

# PRESENCE
vacation_mode:
  name: Vacation Mode
  initial: off
  icon: mdi:airplane
guest_mode:
  name: Guest Mode
  initial: off
  icon: mdi:account-multiple

alarmweekday:
  name: Weekdays Only
  initial: off
  icon: mdi:calendar

# SabNZBD
sabnzbd_turtle_mode:
  name: SabNZBD Turtle Mode
  initial: off 
