- platform: limitlessled
  bridges:
    - host: 192.168.0.25
      version: 5
      port: 8899
      groups:
       - number: 1
         name: Fridge
       - number: 2
         name: Globes
       - number: 3
         name: Floor Lamp
       - number: 4
         name: Stove
#
# esp8266 Chinese bulb with AiLight firmware
#
- platform: mqtt_json
  name: 'Crawl Space'
  state_topic: 'light/entry'
  command_topic: 'light/entry/set'
  color_temp: true
  brightness: true
  rgb: true
  white_value: true
  effect: false
  optimistic: false
#
# milight-esp8266-hub in JSON-MQTT mode
#
- platform: mqtt_json
  name: 'Entry'
  command_topic: 'milight/0x2000/rgbw/1'
  brightness: true
  rgb: true
- platform: mqtt_json
  name: 'Office Pendant'
  command_topic: 'milight/0x1/rgbw/1'
  brightness: true
  rgb: true
- platform: mqtt_json
  name: 'Dining Floor Lamp'
  command_topic: 'milight/0x8000/rgbw/1'
  brightness: true
  rgb: true


# BruhNode LED

- platform: mqtt_json  
  name: "Notify LED"  
  state_topic: "BruhNode/LivingRoom"  
  command_topic: "BruhNode/LivingRoom/set"  
  brightness: true  
  flash: true  
  rgb: true  
  optimistic: false  
  qos: 0 
