- platform: limitlessled
  bridges:
    - host: 192.168.0.25
      version: 5
      port: 8899
      groups:
       - number: 1
         name: Fridge
       - number: 2
         name: Globes
       - number: 3
         name: Floor Lamp
       - number: 4
         name: Stove
    - host: 192.168.0.20
      version: 5
      port: 8003
      groups:
       - number: 1
         name: Office Pendant
    - host: 192.168.0.20
      version: 5
      port: 8004
      groups:
       - number: 1
         name: Entry
    - host: 192.168.0.20
      version: 5
      port: 8005
      groups:
       - number: 1
         name: Dining Floor Lamp

#
# esp8266 Chinese bulb with AiLight firmware
#
- platform: mqtt_json
  name: 'Crawl Space'
  state_topic: 'light/entry'
  command_topic: 'light/entry/set'
  color_temp: true
  brightness: true
  rgb: true
  white_value: true
  effect: false
  optimistic: false

# BruhNode LED

- platform: mqtt_json  
  name: "Notify LED"  
  state_topic: "BruhNode/LivingRoom"  
  command_topic: "BruhNode/LivingRoom/set"  
  brightness: true  
  flash: true  
  rgb: true  
  optimistic: false  
  qos: 0 
