  exclude:
    entities:
      - sensor.cpu_temperature
      - sensor.cpu_use
      - sensor.disk_free_
      - sensor.disk_use_
      - sensor.pihole
      - sensor.pihole_domains_blocked
      - sensor.pihole_percentage_today
      - sensor.pihole_queries_today
      - sensor.ram_use
      - sensor.sabnzbd_disk
      - sensor.sabnzbd_disk_free
      - sensor.sabnzbd_left
      - sensor.sabnzbd_queue
      - sensor.sabnzbd_speed
      - sensor.sabnzbd_status
      - sensor.since_last_boot
      - sensor.synology_storage
      - sensor.synology_storage_free
      - sensor.transmission_down_speed
      - sensor.transmission_down_speed_kbps
      - sensor.transmission_status
      - sensor.transmission_up_speed
      - sensor.transmission_up_speed_kbps
      - sensor.transmission_turtle_mode
      - sensor.dark_sky_icon
      - sensor.time_utc
      - sensor.date__time
      - sensor.time__date
      - sensor.time
      - group.Kitchen
      - group.Motion
      - automation.publish_aquarium_to_thingspeak
      - automation.publish_window_light_level_to_thingspeak
      - automation.publish_plants_to_thingspeak
      - binary_sensor.ecolink_pir_motion_sensor_sensor_14_0
