#
# Audible Notifications
#

# If door opens while I'm home and 'armed home' is set
- alias: 'Alarm Announce - Door Open'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'open'
  condition:
    - condition: state
      entity_id: group.tracked_users
      state: 'on'
    - condition: state
      entity_id: alarm_control_panel.loft_alarm
      state: 'armed home'
  action:
    service: shell_command.alarm_sound_doorchime

# If alarm changes from 'disarmed' to 'pending' announce 
# Only announce if I'm home to hear it
- alias: 'Alarm Announce - Pending Arm'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.loft_alarm
      to: 'pending'
  condition:
    - condition: state
      entity_id: group.tracked_users
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.mpd_pi
    # "Alarm is being armed..." 2s
    - service: shell_command.alarm_sound_armed
    # Beep.. beep. beep.. turn off after done pending state
    - service: script.turn_on
      entity_id: script.alarm_pending_loop

# If alarm changes from 'pending' to 'armed home'
# Turn off pending loop, then announce it
# Not dependent on tracked_users in order to kill loop after I leave
#
- alias: 'Alarm Announce - Armed Home'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.loft_alarm
      to: 'armed_home'
  action:
    - delay: "00:00:01"
    - service: shell_command.alarm_sound_alarm_is_armed_home

# If alarm changes from 'pending' to 'armed away'
# Turn off pending loop, then announce it
#
- alias: 'Alarm Announce - Armed Away'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.loft_alarm
      to: 'armed_away'
  action:
    - delay: "00:00:01"
    - service: shell_command.alarm_sound_alarm_is_armed    


# If alarm is disarmed, announce
# Only if I'm home to hear it
- alias: 'Alarm Announce - Disarmed'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.loft_alarm
      to: 'disarmed'
  condition:
    - condition: state
      entity_id: group.tracked_users
      state: 'on'
  action:
    - delay: "00:00:01"
    - service: shell_command.alarm_sound_disarmed
    

#
#
# Alarm Triggers
#
#


#
# Change Alarm Status based on presence
# Arm Away when I leave, Arm Home when I arrive home
#
# Turning on guest_mode disables these
# So status stays what I leave it even if I come/go
#

# If tracked_users leave and no guests are here, arm away
- alias: 'Alarm - House Empty, Arm Away'
  trigger:
    - platform: state
      entity_id: group.tracked_users
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.alarm_arm_away

- alias: 'Alarm - Arm Home'
  trigger:
    - platform: state
      entity_id: group.tracked_users
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.alarm_arm_home
