#
# Automations based on Dash buttons
#
# Events are sent thrown Dasher
# https://github.com/maddox/dasher
# http://www.bruhautomation.com/single-post/2016/11/22/How-To-Use-an-Amazon-Dash-with-IFTTT-and-Home-Assistant
#


#
# Too lazy to redo this trigger so this is it
#
- alias: 'Laundry Timer'
  trigger:
    platform: event
    event_type: laundry_timer
  action:
    - service: script.turn_on
      entity_id: script.laundry_timer
