#
# Update Meta Device Tracker
#
- alias: "Update Brad's Meta Tracker"
  trigger:
    - platform: state
      entity_id: device_tracker.brad_ios, device_tracker.brad_owntracks, device_tracker.brad_ping
    - platform: homeassistant
      event: start
  action:
    service: python_script.meta_device_tracker
    data_template:
      entity_id: '{{trigger.entity_id}}' 
      meta_entity: 'Brad'

#
# Turn on evening lighting if someone is home at SUNSET
#
- alias: 'Sunset Transition'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:40:00"
  condition:
    condition: state
    entity_id: group.tracked_users
    state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.evening_bright_lights

#
# Turn on lights when someone comes home
#
- alias: 'Welcome Home - Day'
  trigger:
    platform: state
    entity_id: group.tracked_users
    from: 'not_home'
    to: 'home'
  condition:
    - condition: sun
      after: sunrise
    - condition: sun
      before: sunset
  action:
    - service: scene.turn_on
      entity_id: scene.day_dim_lights
    - service: homeassistant.turn_on
      entity_id: switch.transmission_turtle_mode

# Same thing but differnet scene for evening 
- alias: 'Welcome Home - Evening'
  trigger:
    platform: state
    entity_id: group.tracked_users
    from: 'not_home'
    to: 'home'
  condition:
    - condition: sun
      after: sunset
    - condition: sun
      after: sunrise
  action:
    - service: scene.turn_on
      entity_id: scene.night_dim_lights
    - service: homeassistant.turn_on
      entity_id: switch.transmission_turtle_mode

# Same thing but differnet scene for Midnight-430am
- alias: "Welcome Home - It's Pretty Late"
  trigger:
    platform: state
    entity_id: group.tracked_users
    from: 'not_home'
    to: 'home'
  condition:
    - condition: time
      before: '05:30:00'
  action:
    - service: scene.turn_on
      entity_id: scene.night_light

#
# TURN EVERYTHING OFF WHEN NO ONE IS HOME
#
# IF no one is home, turn off the lights and bandwidth throttles
# If no one is home & NPR is playing, turn off NPR
- alias: See Ya Later
  trigger:
    platform: state
    entity_id: group.tracked_users
    to: 'not_home'
  action:
    - service: scene.turn_on
      entity_id: scene.all_lights_off
