#
# Run scripts at start
#

#
# Turn on/off UI elements
#

# Turn Visibility Off for These Groups at HA start
- alias: 'UI Groups Off by Default'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: group.set_visibility
      entity_id: group.traveltimes, group.TodayWeather, group.TodayDefault
      data:
        visible: False
